### ISSUE TITLE
Test SNAP as our standard implementation graph library

### ISSUE THREAD

**Issue by phoeinx** [robinwersich/iPregel#6]
Required algorithms:

- [ ] SSSP
- [ ] PageRank
- [ ] Betweenness Centrality
- [ ] Closeness Centrality

Required:

- [ ] Get running on Ligra Graph format
- [ ] opt. get running on ScoreLab

**Comment by robinwersich** [comment]
SNAP seems to interpret directed graphs as undirected.
As we could not solve this error, it is currently unsuitable as our standard implementation graph library.
